const images = [
    new image(
        "https://c.tenor.com/x8v1oNUOmg4AAAAd/rickroll-roll.gif",
        "image 1",
        "image 1 description Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        [
            "image 1 description Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam et neque ut ante bibendum blandit vehicula eu nulla. In hac habitasse platea dictumst. Nullam eros libero, viverra ac felis id, luctus congue turpis. Nulla feugiat eros vel sapien fermentum condimentum. Vestibulum suscipit justo at pulvinar sollicitudin. Nam consectetur ex et quam suscipit, ac facilisis turpis fringilla. Suspendisse euismod libero ac malesuada lobortis. Etiam vitae finibus eros. Ut rutrum, nulla non mattis sodales, orci eros condimentum diam, eu rutrum mauris arcu eget sem. Pellentesque laoreet justo ac lobortis facilisis. Mauris vestibulum dapibus quam non commodo. Aenean arcu velit, volutpat ut ipsum et, aliquet finibus nisi. Donec lacinia et ex sed ultrices. Vivamus odio ligula, semper et tortor ut, porttitor placerat odio. Sed volutpat pulvinar sapien, in pulvinar urna auctor et. Cras eros orci, pulvinar eu malesuada in, blandit quis eros.",
            "Sed in dolor id dolor varius dapibus non vitae risus. Praesent placerat mi eu iaculis fermentum. Morbi quis sodales ligula, sed venenatis urna. Curabitur pellentesque sagittis leo quis maximus. Etiam maximus, mauris in gravida aliquet, neque risus euismod mauris, at tincidunt velit neque ac nunc. Sed mattis justo rhoncus dictum porttitor. Ut ultricies urna erat, ut volutpat nibh cursus ut. Pellentesque vitae mauris arcu. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque et enim tortor.",
            "Donec volutpat, metus nec interdum condimentum, tellus enim pellentesque est, sit amet elementum eros elit non est. Suspendisse varius massa vitae quam lacinia, nec malesuada nibh posuere. Nullam et justo nec odio euismod molestie sit amet eget justo. Sed tristique dignissim lacinia. Proin aliquam dui neque, auctor bibendum nisl congue in. Cras eu nibh et nisl pharetra euismod. Donec feugiat accumsan leo, ut porttitor diam sagittis nec. Vivamus aliquam a sem vitae vulputate. Pellentesque tempus augue vel dui feugiat, a euismod risus tincidunt."
        ]
    ),
    new image(
        "https://upload.wikimedia.org/wikipedia/commons/3/3f/Totally_not_a_Rickroll_QR_code.png", 
        "image 2", 
        "image 2 description Cras consequat ipsum arcu, in faucibus est vehicula ut.", 
        [
            "image 2 description Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc elementum volutpat erat sed sollicitudin. Phasellus vel sem elit. Mauris interdum magna nunc, in volutpat sem ultrices pretium. Sed molestie tristique tincidunt. Vivamus scelerisque ipsum ultrices ex eleifend lacinia. Donec facilisis leo ut dui laoreet pellentesque. Sed magna tortor, commodo consectetur dictum accumsan, ultricies et magna. Integer elit ex, accumsan eget condimentum sit amet, volutpat consequat lectus. Cras convallis mi consequat luctus ullamcorper. Aenean consectetur dui vitae tempor posuere. Nam in rhoncus neque.",
            "Pellentesque tincidunt viverra dapibus. Pellentesque ultrices efficitur neque nec hendrerit. Ut tortor turpis, viverra eu faucibus ac, malesuada in odio. Aenean dignissim urna eget dignissim vulputate. Sed vel nibh vitae tellus sagittis blandit. Fusce diam leo, commodo ac tincidunt nec, eleifend a lectus. Suspendisse mattis at est ac viverra. Ut in nisl purus. Suspendisse potenti. Nulla volutpat urna dignissim, maximus dui eget, egestas ligula. Nulla finibus metus diam, eu rutrum neque porta tempor.",
            "Nunc quis nibh in turpis gravida ultrices. Sed eget turpis sed quam sodales ultricies. Aliquam a pharetra lacus. Nulla sit amet augue nisi. Mauris et dictum tellus. Proin rhoncus eros sed urna fermentum, facilisis egestas nisi sodales. Praesent et nisl ligula. Nulla commodo pellentesque magna, sed mattis magna condimentum a. Proin quis gravida justo. Nullam a lorem maximus, lobortis ante ac, placerat elit. Praesent congue, augue et ornare cursus, velit mauris aliquam leo, vel tempor lacus tellus sed metus. Maecenas eget ante sit amet ex interdum hendrerit ac hendrerit ipsum. Aliquam dignissim est sit amet consequat rutrum. Phasellus in sem molestie, rhoncus odio vitae, scelerisque sem. Phasellus in ultricies tortor. Nullam lobortis diam ut gravida rutrum."
        ]
    ),
    new image(
        "https://upload.wikimedia.org/wikipedia/en/thumb/f/f7/RickRoll.png/250px-RickRoll.png",
        "image 3",
        "image 3 description Donec lobortis nec quam id finibus.",
        [
            "image 3 description Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum, libero eu consequat viverra, metus arcu varius massa, a mollis nibh metus ut neque. Aliquam erat volutpat. Integer metus turpis, finibus nec maximus ut, vehicula eget libero. Etiam semper arcu sed vestibulum sagittis. Donec neque urna, ultrices eget volutpat vel, tincidunt ac ex. Mauris bibendum auctor eros eget placerat. Duis sed volutpat magna.",
            "Fusce sollicitudin maximus accumsan. Sed non sapien scelerisque, euismod quam id, vulputate tellus. Suspendisse in rhoncus leo, in finibus sem. Mauris tempus nunc urna, eget volutpat nisi semper a. Nullam a leo posuere, ornare urna eu, tincidunt mauris. Morbi et risus et urna dapibus tincidunt quis quis nisl. Proin dictum enim turpis, quis ornare ex consequat nec. Vestibulum id mi turpis. Morbi rhoncus orci egestas fringilla vehicula. Proin aliquam, leo sit amet rhoncus tempor, tortor magna placerat augue, nec hendrerit nibh leo id lacus. Quisque erat nunc, hendrerit ut lacinia vitae, pretium dapibus ligula. Phasellus et nulla blandit, porta ex quis, ultrices mauris. Duis id faucibus lectus. Duis rhoncus facilisis justo at facilisis.",
            "Phasellus tincidunt efficitur fringilla. Donec ut faucibus massa. Quisque in pharetra turpis. Proin est magna, tristique et velit eget, ultricies maximus lorem. Proin ultrices dolor velit, sed aliquam nulla tempor in. Duis leo mauris, varius eget metus nec, finibus efficitur neque. Sed nec urna leo. Sed bibendum, arcu vel fermentum commodo, ante lacus ultrices urna, eu iaculis justo est ac velit. Integer ipsum magna, viverra nec lectus et, suscipit ornare neque. Sed tempus eros libero, nec iaculis dui bibendum eu. Duis vulputate, diam in venenatis feugiat, leo leo malesuada ex, convallis gravida erat massa sed lorem. Mauris eget nisl malesuada, congue diam tincidunt, dictum elit. Maecenas in est dignissim, mollis lorem ut, fermentum nibh."
        ]
    ),
    new image("https://i.kym-cdn.com/news/posts/desktop/000/001/299/cover11.jpg", "image 4", "image 4 description Proin venenatis tellus eu lacus hendrerit, id posuere lorem imperdiet.",
    [
        "image 4 description Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis luctus ultricies ultricies. Nunc porttitor a nunc nec fermentum. Nulla in eleifend augue, eget blandit erat. Donec feugiat id sapien vel varius. Vestibulum posuere nisl velit, a ultricies tellus condimentum imperdiet. Phasellus id eleifend turpis, sit amet laoreet lorem. Sed viverra mauris eget tellus tristique, id dictum urna porttitor. Vivamus egestas condimentum egestas. Donec eleifend ipsum leo, vitae auctor diam pharetra ac. Morbi a mollis nunc. Etiam tristique lorem nisl, non porttitor lorem faucibus in.",
        "Sed et diam nulla. Quisque ac sem sit amet quam venenatis dapibus. Quisque facilisis nibh et odio rutrum commodo. Donec tristique, elit ut rutrum ultrices, nibh metus scelerisque arcu, in sollicitudin justo purus id dui. Morbi enim odio, tempus sed nibh vitae, eleifend bibendum ex. Vivamus pretium auctor orci, dictum porttitor diam iaculis vitae. Maecenas ac imperdiet sem. Ut ultricies ornare ligula id scelerisque. Maecenas at nibh mauris. Sed malesuada vel lorem et cursus. Quisque ac placerat ex. Vivamus semper ipsum sit amet dui auctor euismod. Quisque posuere odio ac quam varius interdum. Suspendisse at congue risus, non vehicula nisl.",
        "Aenean eget justo risus. Nulla dui odio, vulputate vel hendrerit quis, auctor a quam. Ut mauris risus, mattis ac pretium non, egestas ut libero. Cras rutrum sed leo id eleifend. Aenean suscipit orci eget velit faucibus venenatis. Vestibulum ultricies eros turpis, eu pulvinar odio euismod sed. Duis odio tortor, dictum ut tempor ullamcorper, egestas a turpis. Proin finibus velit orci, nec hendrerit lacus feugiat vel. Pellentesque tortor nisl, auctor a libero id, sodales posuere justo. Integer non massa posuere, finibus mi nec, commodo nulla. Nulla aliquam tempus tempus. Duis lobortis ante fermentum, scelerisque neque a, lobortis nisi. Cras porta ligula fermentum ante tincidunt dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum urna nisl, pretium a dignissim nec, luctus in felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos."
    ]),
    new image("https://s.yimg.com/ny/api/res/1.2/aMLVoTIHrDS1J91FuAW5bg--/YXBwaWQ9aGlnaGxhbmRlcjt3PTY0MA--/https://s.yimg.com/dh/ap/default/140117/rickroll1.jpg", "image 5", "image 5 description Morbi turpis justo, tempor sit amet nisi a, euismod hendrerit erat.",
    [
        "image 5 description Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque consequat consectetur consequat. Vestibulum at turpis eu neque blandit consequat. Curabitur sodales lacus et turpis porta fermentum. Sed hendrerit velit dui, et ornare dolor dapibus lobortis. Donec eget ornare orci. Aliquam lacus nibh, facilisis id urna sed, molestie rutrum ligula. Ut ac neque et metus consequat ornare vel eu ipsum. Cras pharetra non dolor ac ornare.",
        "Morbi ut dui viverra, maximus erat ultricies, tristique mi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque lobortis lorem et dolor ullamcorper, eget pretium nisl dignissim. Aliquam metus enim, fringilla vitae rutrum eu, consectetur ac massa. Maecenas aliquam dolor ut malesuada ultrices. Sed finibus quis quam eu dictum. Nullam porta tortor vitae sodales porttitor. Integer ultrices ligula elementum volutpat placerat. Donec ut magna et diam vehicula tempor. Pellentesque id odio eget libero eleifend condimentum. Etiam eget felis ac turpis vehicula cursus. Pellentesque laoreet felis ipsum, vitae imperdiet mauris rhoncus semper. Integer rutrum, tortor non sollicitudin congue, orci enim commodo leo, eu vestibulum massa mi id nisi.",
        "Integer sollicitudin, ex vitae dictum cursus, velit erat ullamcorper lectus, a tempus sem sem id diam. Aliquam mi metus, vulputate id fermentum vitae, ultrices vel lorem. Phasellus volutpat congue mollis. Ut id turpis ac elit ultricies pulvinar ac a arcu. In interdum scelerisque fringilla. Aliquam ultricies urna eget sem dignissim dignissim sit amet eu mauris. Donec eleifend urna sit amet dui lobortis, et vulputate mi sodales. Quisque et luctus risus. Proin ligula arcu, ultricies quis ultricies vitae, condimentum eu mauris. Pellentesque sed euismod purus. Vestibulum diam ex, vehicula cursus sodales vel, condimentum pellentesque dui. Sed a commodo arcu. Vivamus sed erat urna. Fusce pretium arcu eget libero convallis efficitur. Vivamus eleifend, nunc vitae vulputate rutrum, arcu elit commodo lectus, sit amet maximus elit neque vel dui. Nulla venenatis tincidunt sapien eu pulvinar."
    ])
]